${HOME}/Apps/ephemeris/jplget.sh -21
${HOME}/Apps/ephemeris/jplget.sh -61
${HOME}/Apps/ephemeris/jplget.sh -64
${HOME}/Apps/ephemeris/jplget.sh -74
${HOME}/Apps/ephemeris/jplget.sh -95
${HOME}/Apps/ephemeris/jplget.sh -96
${HOME}/Apps/ephemeris/jplget.sh -121
${HOME}/Apps/ephemeris/jplget.sh -144
${HOME}/Apps/ephemeris/jplget.sh -170
${HOME}/Apps/ephemeris/jplget.sh -227
${HOME}/Apps/ephemeris/jplget.sh -234
${HOME}/Apps/ephemeris/jplget.sh -235
${HOME}/Apps/ephemeris/jplget.sh -557
${HOME}/Apps/ephemeris/jplget.sh -139479
${HOME}/Apps/ephemeris/jplget.sh 299
${HOME}/Apps/ephemeris/jplget.sh 391
${HOME}/Apps/ephemeris/jplget.sh 392
${HOME}/Apps/ephemeris/jplget.sh 499
${HOME}/Apps/ephemeris/jplget.sh 599
${HOME}/Apps/ephemeris/jplget.sh 699
${HOME}/Apps/ephemeris/jplget.sh 101955
${HOME}/Apps/ephemeris/jplget.sh 162173
